import { Navbar } from "@/components/Navbar"
import { Inter } from 'next/font/google'
import '@/styles/global.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
    
}

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <head>
                <link rel="icon" href="/icons/icons8-e-50.ico" />
            </head>
            <body className={`${inter.className} h-screen`}>
                <Navbar />
                <div className="w-11/12 pt-10 pb-10 mx-auto">
                    {children}
                </div>
            </body>
        </html>
    )
}
